### ISSUE TITLE
for nomad case can we mark node as ineligible

### ISSUE THREAD

**Issue by thatsk** [ngine-io/chaotic#10]
for chaos perspective we should make node as ineligible so that workload shift to another node.

**Comment by resmo** [comment]
hmm, that sounds interesting. We were only thinking about bringing chaos to the workload and didn't think about the nodes and the cluster.

**Comment by thatsk** [comment]
https://developer.hashicorp.com/nomad/api-docs/nodes#drain-node
https://developer.hashicorp.com/nomad/api-docs/nodes#purge-node

**Comment by thatsk** [comment]
can we also test this out if you contribute I would be happy to test this out

**Comment by thatsk** [comment]
@resmo any thoughts on this?

**Comment by resmo** [comment]
@thatsk let's clarify that we understand the same: chaotic should drain a node (workload gets shifted), wait some time and then marking the node as eligible for scheduling again, right?

**Comment by thatsk** [comment]
yup exactly the same and if we can add some timing as a parameter for what we have done for a job that would be awesome. for eg. Drain the node for 5 min.

**Comment by thatsk** [comment]
like `allow_node_drainlist:`  i am also assuming that we need to add `skip_node_drainlist:` which is like infra components which don't need to be drained but its optional.

**Comment by thatsk** [comment]
so that workload should be shifted to another workload and once timing has been achieved it should bring back to the original one which is a feature of nomad or wait for that node to be healthy so that we can perform restart stanza and update stanza to be checked

**Comment by resmo** [comment]
first implementation in #16, I only implemented a skip list, but wouldn't be much work to change it to an allow/block list.

**Comment by thatsk** [comment]
I just think now don't we drain the full node or add a parameter to tag with the system job to be drained or not via `config.yaml` when I am testing this I think if the node is not eligible for workload then it might be the case the node should be performing an OS upgrade might be I'm not sure.

**Comment by thatsk** [comment]
right now it's performing serially one by one what if we want to perform 20% out of cluster clients or 30%clients to be drained at time in terms of percentage

**Comment by thatsk** [comment]
its just an idea feel free to feedback me

**Comment by thatsk** [comment]
because I am thinking of when autoscaling is performing it might get utilized and trigger an event for to scale up the instance until our instances are eligible for workload

**Comment by resmo** [comment]
I refactored a bit #16 to have it included into the nomad kind and not in a separate nomad_node kind.

> I just think now don't we drain the full node or add a parameter to tag with the system job to be drained or not via `config.yaml` when I am testing this I think if the node is not eligible for workload then it might be the case the node should be performing an OS upgrade might be I'm not sure.

We could add a tag for also draining system jobs, however, I currently see a real usecase for it.

The implementation in #16 does filter out [drained or ineligible nodes](https://github.com/ngine-io/chaotic/pull/16/files#diff-9c235b316919109d6c2684c3ae9ebfb8674dd29330c0d610ac26b67e532b1caeR40)

> right now it's performing serially one by one what if we want to perform 20% out of cluster clients or 30%clients to be drained at time in terms of percentage

The question is, what is our goal with these experiments, this experiment would target the capacity planning of a cluster and might result in a n-service downtime. 

Currently out goal is to test randomly picked services, VMs, nodes  to test for redundancy and failure without impact a huge amount of services or the business service availability in an uncontrolled manner.

However, I think this experiment can be useful for multiple cluster failover experiments, but currently not our main focus.

> because I am thinking of when autoscaling is performed it might get utilized and trigger an event to scale up the instance until our instances are eligible for workload

Not sure if I get what you are thinking. Could you describe in more detail?

**Comment by thatsk** [comment]
yes, that is correct whatever you are saying totally makes sense. the implementation which you have done is applicable in a single cluster. But I am thinking about multi-region and multi-cluster deployment in that we can perform stress on clusters, not on the node level but it's okay whatever implementation right now totally makes sense.

regarding the draining system job I don't see any tag in the config.yaml not sure if its there in code or not.

**Comment by resmo** [comment]
I think, it wouldn't be too hard to implement an option and calculate the % of nodes to be drained, let me check that.

Adding a config option for system jobs draining.

**Comment by resmo** [comment]
also drain system job option https://github.com/ngine-io/chaotic/pull/16/commits/0f5b0966ad83045190822456bcf39d41f54fd898

**Comment by resmo** [comment]
drain multiple nodes in % https://github.com/ngine-io/chaotic/pull/16/commits/edf54f9558932d7208dff2e76fca19ae66a0da63
